title: red-sprout blog       # 블로그 이름
description: red-sprout’s personal tech blog  # 설명 (원하시면 바꿔드립니다)
url: "https://red-sprout.github.io"  # GitHub Pages 주소
baseurl: ""                  # 사용자 페이지는 빈 값으로 유지

author:
  name: 주재완
  github: red-sprout         # GitHub 링크

version:          1.0
gitbook_version:  3.2.3

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

# GitHub Pages 호환용 설정
github:
  is_project_page: false     # 사용자 페이지이므로 false

# 소셜 링크 (footer 등에 노출)
footer_links:
  - title: GitHub
    url: https://github.com/red-sprout

# Google Analytics는 설정 시 ID 추가
google_analytics: ""